version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=529625914815.dkr.ecr.us-east-1.amazonaws.com/dockerpush
       #get timestamp for the tag 
       timestamp=$(date +%Y-%m-%d.%H:%M:%S)
       echo 'Inside PreBuild: " $timestamp
    
  build:
    commands:
       echo 'Inside Build " $timestamp

