version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase...
    
    script:
      - docker build -t mathandotcom/samplenode:latest .
      - docker push mathandotcom/samplenode:latest
