version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - TIMESTAMP=$(date +%Y-%m-%d.%H:%M:%S)
      - echo $TIMESTAMP
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $TIMESTAMP
