version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=529625914815.dkr.ecr.us-east-1.amazonaws.com/dockerpush
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - echo $TIMESTAMP
      - TAG=$REPOSITORY_URI:$TIMESTAMP
      - echo $TAG
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $TIMESTAMP
      - docker build -t $TAG .
      - docker tag $TAG $TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $TAG
      - echo Writing image definitions file...
